**Lab 1**

In [ ]:
#1.To perfrome Tokenization of a given sentence
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')
example="Good morning everyone. Today we will study NLTK."
print(sent_tokenize(example))
print(word_tokenize(example))
for i in (sent_tokenize(example)):
  print (i)
  for j in (word_tokenize(i)):
    print (j)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Good morning everyone.', 'Today we will study NLTK.']
['Good', 'morning', 'everyone', '.', 'Today', 'we', 'will', 'study', 'NLTK', '.']
Good morning everyone.
Good
morning
everyone
.
Today we will study NLTK.
Today
we
will
study
NLTK
.


**Lab 2**

In [ ]:
# 2. To find the stopwords of a given text
import nltk.corpus
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download("stopwords")
stop_words=set(stopwords.words("english"))
print(stop_words)
words=word_tokenize(example)
remove_stopwords=[]
for i in words:
  if i not in stop_words:
    remove_stopwords.append(i)
print(remove_stopwords)
remove_words=[]
remove_words= [i for i in words if i in stop_words]
print(remove_words)


{'has', 'again', 'the', "should've", 'his', 'yourself', 'had', 'but', 'you', 'up', 'because', 'each', 'of', 'that', 'been', 'who', 'those', 'against', 'not', 'i', 'he', 'at', 'in', 'are', 'yours', 'from', 'into', 'below', 'be', 'during', 'it', 'having', 'ours', 'an', 'between', 'were', 'this', 'myself', 'your', "doesn't", 'off', "won't", 'most', 'whom', 'for', "that'll", 'ma', 'nor', 'and', "shan't", 'just', 'm', 'don', 'should', 'didn', "shouldn't", "haven't", 'which', 'once', 'while', 'some', 'through', 't', 'on', 'me', 'him', 'only', 'her', 'before', 'where', 'after', 'himself', "didn't", 'all', 'will', 'have', 'same', 'hasn', 'or', "needn't", 'then', "you'd", 'was', 'with', "don't", 'mightn', 'couldn', 'few', 'my', 'theirs', "hasn't", 'their', "you've", 'out', 'a', 'd', 'll', 'they', 'by', 'being', 'now', 'both', "mightn't", "wouldn't", 're', 'themselves', "hadn't", 'she', 'no', 'ain', "you're", 'under', 'until', 'how', 'than', 've', "weren't", 'itself', 'weren', 'why', 'haven', "a

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


**Lab 3**

In [ ]:
#3. To perform stemming operation using NLTK
import nltk.stem
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
ps=PorterStemmer()
sb=SnowballStemmer(("english"))
words= ["Computer","Computerization","Computerize"]
for i in words:
  print(i+":" +ps.stem(i))
print("---------")
for i in words:
  print(i+":" +sb.stem(i))


Computer:comput
Computerization:computer
Computerize:computer
---------
Computer:comput
Computerization:computer
Computerize:computer


**Lab 4**

In [ ]:
# 4. To perfrom POS tagging of a given text
import nltk.stem
from nltk.corpus import state_union
from nltk.tokenize import sent_tokenize
nltk.download("averaged_perceptron_tagger")
nltk.download('state_union')
from nltk.tokenize import PunktSentenceTokenizer
text= state_union.raw("2005-GWBush.txt")
text="Good morning everyone. Today we will study NLTK."
custom_sent_tokenizer1= sent_tokenize(text)
print(custom_sent_tokenizer1)
custom_sent_tokenizer= PunktSentenceTokenizer(text)
tokenized= custom_sent_tokenizer.tokenize(text)
print(tokenized)
def process_content():
  try:
    for i in tokenized:
      words= nltk.word_tokenize(i)
      tagged= nltk.pos_tag(words)
      print(tagged)
  except Exception as e:
   print(str(e))
process_content()


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package state_union to /root/nltk_data...
[nltk_data]   Unzipping corpora/state_union.zip.


['Good morning everyone.', 'Today we will study NLTK.']
['Good morning everyone.', 'Today we will study NLTK.']
[('Good', 'JJ'), ('morning', 'NN'), ('everyone', 'NN'), ('.', '.')]
[('Today', 'NN'), ('we', 'PRP'), ('will', 'MD'), ('study', 'VB'), ('NLTK', 'NNP'), ('.', '.')]


**Lab 5**

In [ ]:
#5. Take two sentence from 'austen-emma.text' and then perfrom stemming
import nltk
import requests
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer

# Corrected URL
url = "https://raw.githubusercontent.com/fbkarsdorp/Python-Course/master/data/austen-emma.txt"

response = requests.get(url)
text = response.text  # Use .text attribute to get the content

nltk.download('punkt')

ps = PorterStemmer()

# Tokenizing sentences
tokenized_sentences = sent_tokenize(text)

# Selecting specific sentences
selected_sentences = tokenized_sentences[3:5]

for sentence in selected_sentences:
    words = word_tokenize(sentence)
    stemmed_words = [ps.stem(word) for word in words]
    stemmed_sentence = ' '.join(stemmed_words)
    print(stemmed_sentence)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


sixteen year had miss taylor been in mr. woodhous 's famili , less as a gover than a friend , veri fond of both daughter , but particularli of emma .
between _them_ it wa more the intimaci of sister .


In [ ]:
#5. Take two sentence then perfrom stemming
import nltk.stem
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
ps=PorterStemmer()
sb=SnowballStemmer(("english"))
words= ["Computer","Computerization","Computerize"]
for i in words:
  print(i+":" +ps.stem(i))
print("---------")
for i in words:
  print(i+":" +sb.stem(i))

Computer:comput
Computerization:computer
Computerize:computer
---------
Computer:comput
Computerization:computer
Computerize:computer


In [ ]:
# 6,11 Ngram in given text or sentence
import nltk
from nltk.util import ngrams
import nltk
nltk.download('punkt')
#import bigrams, trigrams, ngrams
text="Good morning everyone. Today we will study NLTK. Good afternoon everyone."
tokens=nltk.word_tokenize(text)
# bigrams_list=list(nltk.bigrams(tokens))
# print(bigrams_list)

ngrams_list=list(nltk.ngrams(tokens,3))##
print(ngrams_list)


[('Good', 'morning', 'everyone'), ('morning', 'everyone', '.'), ('everyone', '.', 'Today'), ('.', 'Today', 'we'), ('Today', 'we', 'will'), ('we', 'will', 'study'), ('will', 'study', 'NLTK'), ('study', 'NLTK', '.'), ('NLTK', '.', 'Good'), ('.', 'Good', 'afternoon'), ('Good', 'afternoon', 'everyone'), ('afternoon', 'everyone', '.')]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [15]:
#7.  To perfrom  Tokenization and POS tagging from 'austen-emma.text'
import nltk.stem
from nltk.corpus import state_union
from nltk.tokenize import sent_tokenize
nltk.download("averaged_perceptron_tagger")
nltk.download('state_union')
from nltk.tokenize import PunktSentenceTokenizer
text= state_union.raw("2005-GWBush.txt")
text="Good morning everyone. Today we will study NLTK."
custom_sent_tokenizer1= sent_tokenize(text)
print(custom_sent_tokenizer1)
custom_sent_tokenizer= PunktSentenceTokenizer(text)
tokenized= custom_sent_tokenizer.tokenize(text)
print(tokenized)
def process_content():
  try:
    for i in tokenized:
      words= nltk.word_tokenize(i)
      tagged= nltk.pos_tag(words)
      print(tagged)
  except Exception as e:
   print(str(e))
process_content()


['Good morning everyone.', 'Today we will study NLTK.']
['Good morning everyone.', 'Today we will study NLTK.']
[('Good', 'JJ'), ('morning', 'NN'), ('everyone', 'NN'), ('.', '.')]
[('Today', 'NN'), ('we', 'PRP'), ('will', 'MD'), ('study', 'VB'), ('NLTK', 'NNP'), ('.', '.')]


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package state_union to /root/nltk_data...
[nltk_data]   Unzipping corpora/state_union.zip.


In [8]:
# 8. To perfrom the named Entity recognition using the chunking method
nltk.download('maxent_ne_chunker')
nltk.download('words')
from nltk import ne_chunk
from nltk.tokenize import PunktSentenceTokenizer
train_text=" Sundaram Pichai is a CEO of GOOGLE Company"
sample_text=" Sundaram Pichai is a CEO of GOOGLE Company"
custom_sent_tokenizer= PunktSentenceTokenizer(train_text)
tokenized= custom_sent_tokenizer.tokenize(sample_text)
print(tokenized)
def process_content():
  try:
     for i in tokenized:
        words= nltk.word_tokenize(i)
        tagged= nltk.pos_tag(words)#('averaged perceptron tagger')
        chunks=nltk.ne_chunk(tagged)
        print(chunks)
        chunks.pretty_print(unicodelines=True)
  except Exception as e:
        print(str(e))
process_content()

[' Sundaram Pichai is a CEO of GOOGLE Company']
(S
  (PERSON Sundaram/NNP)
  (PERSON Pichai/NNP)
  is/VBZ
  a/DT
  CEO/NN
  of/IN
  (ORGANIZATION GOOGLE/NNP Company/NNP))
                     S                                                              
  ┌─────┬─────┬──────┼────────┬───────────┬──────────────────────┐                   
  │     │     │      │      PERSON      PERSON              ORGANIZATION            
  │     │     │      │        │           │          ┌───────────┴────────────┐      
is/VBZ a/DT CEO/NN of/IN Sundaram/NNP Pichai/NNP GOOGLE/NNP              Company/NNP



[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


In [65]:
#9 To perform lemmatization of some given text
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
wrd=WordNetLemmatizer()
print(wrd.lemmatize("better",pos="a"))
print(wrd.lemmatize("better",pos="n"))
print(wrd.lemmatize("is",pos="v"))
print(wrd.lemmatize("is",pos="r"))

good
better
be
is


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [64]:
#10
import nltk
nltk.download('movie_reviews')

from nltk import FreqDist, NaiveBayesClassifier
from nltk.corpus import movie_reviews
from nltk.classify import accuracy
import random

documents = [(list(movie_reviews.words(fileid)), category)
             for category in movie_reviews.categories()
             for fileid in movie_reviews.fileids(category)]

random.shuffle(documents)

all_words = FreqDist(w.lower() for w in movie_reviews.words())
word_features = list(all_words)[:1000]

def document_features(document):
    document_words = set(document)
    features = {}
    for word in word_features:
        features['contains({})'.format(word)] = (word in document_words)
    return features

featuresets = [(document_features(d), c) for (d, c) in documents]
train_set, test_set = featuresets[:900], featuresets[900:]  # Corrected the splitting
classifier = NaiveBayesClassifier.train(train_set)

# Print accuracy and show most informative features
print('Accuracy:', accuracy(classifier, test_set) * 100)
classifier.show_most_informative_features(10)


[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!


Accuracy: 76.0
Most Informative Features
        contains(stupid) = True              neg : pos    =      4.4 : 1.0
     contains(memorable) = True              pos : neg    =      4.0 : 1.0
         contains(worst) = True              neg : pos    =      3.8 : 1.0
           contains(key) = True              pos : neg    =      3.6 : 1.0
          contains(mess) = True              neg : pos    =      3.5 : 1.0
         contains(solid) = True              pos : neg    =      3.2 : 1.0
     contains(perfectly) = True              pos : neg    =      3.2 : 1.0
     contains(excellent) = True              pos : neg    =      3.2 : 1.0
       contains(overall) = True              pos : neg    =      3.0 : 1.0
      contains(supposed) = True              neg : pos    =      2.9 : 1.0


In [9]:
# 12. to perfrom Chuunking operation
from sklearn import tree
from nltk.tree import *
text = "A dog chased a cat"
tokens = nltk.word_tokenize(text)
print(tokens)
tag = nltk.pos_tag(tokens)
print(tag)
grammar = "NP: {<DT>?<JJ>*<NN.*>}"
cp  =nltk.RegexpParser(grammar)
result = cp.parse(tag)
print(result)
print(result.pformat_latex_qtree())
result.pretty_print()


['A', 'dog', 'chased', 'a', 'cat']
[('A', 'DT'), ('dog', 'NN'), ('chased', 'VBD'), ('a', 'DT'), ('cat', 'NN')]
(S (NP A/DT dog/NN) chased/VBD (NP a/DT cat/NN))
\Tree [.S [.NP A/DT dog/NN ] chased/VBD [.NP a/DT cat/NN ] ]
                      S                   
     _________________|__________          
    |            NP              NP       
    |        ____|____       ____|____     
chased/VBD A/DT     dog/NN a/DT     cat/NN



In [13]:
## 13. To show the function of FREDDIST PACKAGE IN NLTK
from nltk import FreqDist
from nltk.tokenize import word_tokenize
from nltk.corpus import gutenberg
from nltk import FreqDist
nltk.download('gutenberg')
# Count each token in austen-persuasion.txt of the Gutenberg collection
list_of_words = gutenberg.words("austen-persuasion.txt")
fd = FreqDist(list_of_words) # Frequency distribution object
print("Total number of tokens: " + str(fd.N())) # <insert_comment_how_many>
print("Number of unique tokens: " + str(fd.B())) # <insert_comment_how_many>
print("Top 10 tokens:") # <insert_comment_which_is_third token>
for token, freq in fd.most_common(10):
  print(token + "\t" + str(freq))

Total number of tokens: 98171
Number of unique tokens: 6132
Top 10 tokens:
,	6750
the	3120
to	2775
.	2741
and	2739
of	2564
a	1529
in	1346
was	1330
;	1290


[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [17]:
#14 RNN
from tensorflow import keras
from tensorflow.keras import layers

x = layers.Input(shape=(12, 7))

cell = layers.SimpleRNNCell(4, activation='tanh')

rnn = layers.RNN(cell)

output_rnn = rnn(x)

output = layers.Dense(1, activation='sigmoid')(output_rnn)

model = keras.Model(inputs=x, outputs=output)
model.compile(loss="binary_crossentropy", metrics=["accuracy"])

model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 12, 7)]           0         
                                                                 
 rnn (RNN)                   (None, 4)                 48        
                                                                 
 dense (Dense)               (None, 1)                 5         
                                                                 
Total params: 53 (212.00 Byte)
Trainable params: 53 (212.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
#15 LSTM
!pip install -q tensorflow-datasets
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow_datasets as tfds
import numpy as np

# Load the IMDb reviews dataset
dataset, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

# Split the dataset into train and test sets
train_dataset, test_dataset = dataset['train'], dataset['test']

# Take a subset of the datasets
train_dataset = train_dataset.take(4000)
test_dataset = test_dataset.take(1000)


BUFFER_SIZE = 9000
BATCH_SIZE = 128


train_dataset = train_dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

test_dataset = test_dataset.batch(BATCH_SIZE)

train_dataset = train_dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

VOCAB_SIZE = 1000
encoder = layers.experimental.preprocessing.TextVectorization(max_tokens=VOCAB_SIZE)
encoder.adapt(train_dataset.map(lambda text, label: text))

example = next(iter(train_dataset.take(1)))

vocab = np.array(encoder.get_vocabulary())
encoded_example = encoder(example[0]).numpy()

# Display the length of the example and the encoded text
print("Length of the example:", len(example[0]))
print("Encoded text:", encoded_example)


Length of the example: 128
Encoded text: [[ 35   1  52 ...   0   0   0]
 [  1   2   1 ...   0   0   0]
 [410   1   7 ...   0   0   0]
 ...
 [ 53   9  74 ...   0   0   0]
 [ 10   7   1 ...   0   0   0]
 [635   6   2 ...   0   0   0]]
